var annotated_dup =
[
    [ "cannon", null, [
      [ "control", "namespacecannon_1_1control.html", "namespacecannon_1_1control" ],
      [ "geom", "namespacecannon_1_1geom.html", "namespacecannon_1_1geom" ],
      [ "graphics", "namespacecannon_1_1graphics.html", "namespacecannon_1_1graphics" ],
      [ "log", "namespacecannon_1_1log.html", "namespacecannon_1_1log" ],
      [ "logic", "namespacecannon_1_1logic.html", "namespacecannon_1_1logic" ],
      [ "math", "namespacecannon_1_1math.html", "namespacecannon_1_1math" ],
      [ "ml", "namespacecannon_1_1ml.html", "namespacecannon_1_1ml" ],
      [ "physics", "namespacecannon_1_1physics.html", "namespacecannon_1_1physics" ],
      [ "plot", "namespacecannon_1_1plot.html", "namespacecannon_1_1plot" ],
      [ "ray", null, [
        [ "Aabb", "classcannon_1_1ray_1_1Aabb.html", "classcannon_1_1ray_1_1Aabb" ],
        [ "Box", "classcannon_1_1ray_1_1Box.html", "classcannon_1_1ray_1_1Box" ],
        [ "BoxFilter", "classcannon_1_1ray_1_1BoxFilter.html", "classcannon_1_1ray_1_1BoxFilter" ],
        [ "BvhNode", "classcannon_1_1ray_1_1BvhNode.html", "classcannon_1_1ray_1_1BvhNode" ],
        [ "Camera", "classcannon_1_1ray_1_1Camera.html", "classcannon_1_1ray_1_1Camera" ],
        [ "CameraSample", "structcannon_1_1ray_1_1CameraSample.html", "structcannon_1_1ray_1_1CameraSample" ],
        [ "CheckerTexture", "classcannon_1_1ray_1_1CheckerTexture.html", "classcannon_1_1ray_1_1CheckerTexture" ],
        [ "ConstantMedium", "classcannon_1_1ray_1_1ConstantMedium.html", "classcannon_1_1ray_1_1ConstantMedium" ],
        [ "Dielectric", "classcannon_1_1ray_1_1Dielectric.html", "classcannon_1_1ray_1_1Dielectric" ],
        [ "DiffuseLight", "classcannon_1_1ray_1_1DiffuseLight.html", "classcannon_1_1ray_1_1DiffuseLight" ],
        [ "Film", "classcannon_1_1ray_1_1Film.html", "classcannon_1_1ray_1_1Film" ],
        [ "FilmPixel", "structcannon_1_1ray_1_1FilmPixel.html", "structcannon_1_1ray_1_1FilmPixel" ],
        [ "FilmTile", "structcannon_1_1ray_1_1FilmTile.html", "structcannon_1_1ray_1_1FilmTile" ],
        [ "Filter", "classcannon_1_1ray_1_1Filter.html", "classcannon_1_1ray_1_1Filter" ],
        [ "GaussianFilter", "classcannon_1_1ray_1_1GaussianFilter.html", "classcannon_1_1ray_1_1GaussianFilter" ],
        [ "GlobalSampler", "classcannon_1_1ray_1_1GlobalSampler.html", "classcannon_1_1ray_1_1GlobalSampler" ],
        [ "hit_record", "structcannon_1_1ray_1_1hit__record.html", "structcannon_1_1ray_1_1hit__record" ],
        [ "Hittable", "classcannon_1_1ray_1_1Hittable.html", "classcannon_1_1ray_1_1Hittable" ],
        [ "HittableList", "classcannon_1_1ray_1_1HittableList.html", "classcannon_1_1ray_1_1HittableList" ],
        [ "ImageTexture", "classcannon_1_1ray_1_1ImageTexture.html", "classcannon_1_1ray_1_1ImageTexture" ],
        [ "Isotropic", "classcannon_1_1ray_1_1Isotropic.html", "classcannon_1_1ray_1_1Isotropic" ],
        [ "Lambertian", "classcannon_1_1ray_1_1Lambertian.html", "classcannon_1_1ray_1_1Lambertian" ],
        [ "Material", "classcannon_1_1ray_1_1Material.html", "classcannon_1_1ray_1_1Material" ],
        [ "Metal", "classcannon_1_1ray_1_1Metal.html", "classcannon_1_1ray_1_1Metal" ],
        [ "MitchellFilter", "classcannon_1_1ray_1_1MitchellFilter.html", "classcannon_1_1ray_1_1MitchellFilter" ],
        [ "MovingSphere", "classcannon_1_1ray_1_1MovingSphere.html", "classcannon_1_1ray_1_1MovingSphere" ],
        [ "NoiseTexture", "classcannon_1_1ray_1_1NoiseTexture.html", "classcannon_1_1ray_1_1NoiseTexture" ],
        [ "NormalDebug", "classcannon_1_1ray_1_1NormalDebug.html", "classcannon_1_1ray_1_1NormalDebug" ],
        [ "PixelSampler", "classcannon_1_1ray_1_1PixelSampler.html", "classcannon_1_1ray_1_1PixelSampler" ],
        [ "Ray", "classcannon_1_1ray_1_1Ray.html", "classcannon_1_1ray_1_1Ray" ],
        [ "Raytracer", "classcannon_1_1ray_1_1Raytracer.html", "classcannon_1_1ray_1_1Raytracer" ],
        [ "raytracer_params", "structcannon_1_1ray_1_1raytracer__params.html", "structcannon_1_1ray_1_1raytracer__params" ],
        [ "Sampler", "classcannon_1_1ray_1_1Sampler.html", "classcannon_1_1ray_1_1Sampler" ],
        [ "SolidColor", "classcannon_1_1ray_1_1SolidColor.html", "classcannon_1_1ray_1_1SolidColor" ],
        [ "Sphere", "classcannon_1_1ray_1_1Sphere.html", "classcannon_1_1ray_1_1Sphere" ],
        [ "StratifiedSampler", "classcannon_1_1ray_1_1StratifiedSampler.html", "classcannon_1_1ray_1_1StratifiedSampler" ],
        [ "Texture", "classcannon_1_1ray_1_1Texture.html", "classcannon_1_1ray_1_1Texture" ],
        [ "Triangle", "classcannon_1_1ray_1_1Triangle.html", "classcannon_1_1ray_1_1Triangle" ],
        [ "TriangleFilter", "classcannon_1_1ray_1_1TriangleFilter.html", "classcannon_1_1ray_1_1TriangleFilter" ],
        [ "TriangleMesh", "classcannon_1_1ray_1_1TriangleMesh.html", "classcannon_1_1ray_1_1TriangleMesh" ],
        [ "XYRect", "classcannon_1_1ray_1_1XYRect.html", "classcannon_1_1ray_1_1XYRect" ],
        [ "XZRect", "classcannon_1_1ray_1_1XZRect.html", "classcannon_1_1ray_1_1XZRect" ],
        [ "YZRect", "classcannon_1_1ray_1_1YZRect.html", "classcannon_1_1ray_1_1YZRect" ]
      ] ],
      [ "utils", "namespacecannon_1_1utils.html", "namespacecannon_1_1utils" ]
    ] ]
];