var hierarchy =
[
    [ "cannon::ray::Aabb", "classcannon_1_1ray_1_1Aabb.html", null ],
    [ "cannon::ml::AdamOptimizer", "classcannon_1_1ml_1_1AdamOptimizer.html", null ],
    [ "cannon::control::AffineController", "classcannon_1_1control_1_1AffineController.html", null ],
    [ "ApprovalWriter", null, [
      [ "cannon::graphics::OpenGLWriter", "classcannon_1_1graphics_1_1OpenGLWriter.html", null ]
    ] ],
    [ "cannon::utils::ArgParser", "classcannon_1_1utils_1_1ArgParser.html", null ],
    [ "cannon::logic::AssignmentHeuristic", "classcannon_1_1logic_1_1AssignmentHeuristic.html", null ],
    [ "cannon::plot::Axes", "classcannon_1_1plot_1_1Axes.html", null ],
    [ "cannon::ml::BFGSOptimizer", "classcannon_1_1ml_1_1BFGSOptimizer.html", null ],
    [ "cannon::math::BigUnsigned", "classcannon_1_1math_1_1BigUnsigned.html", null ],
    [ "cannon::control::Block", "classcannon_1_1control_1_1Block.html", [
      [ "cannon::control::blocks::Add", "classcannon_1_1control_1_1blocks_1_1Add.html", null ],
      [ "cannon::control::blocks::Constant", "classcannon_1_1control_1_1blocks_1_1Constant.html", null ],
      [ "cannon::control::blocks::Gain", "classcannon_1_1control_1_1blocks_1_1Gain.html", null ],
      [ "cannon::control::blocks::Step", "classcannon_1_1control_1_1blocks_1_1Step.html", null ]
    ] ],
    [ "cannon::utils::BlockingQueue< T >", "classcannon_1_1utils_1_1BlockingQueue.html", null ],
    [ "cannon::utils::BlockingQueue< std::shared_ptr< cannon::graphics::ImageData > >", "classcannon_1_1utils_1_1BlockingQueue.html", null ],
    [ "cannon::utils::BlockingQueue< std::shared_ptr< T > >", "classcannon_1_1utils_1_1BlockingQueue.html", null ],
    [ "cannon::graphics::Camera", "classcannon_1_1graphics_1_1Camera.html", null ],
    [ "cannon::ray::Camera", "classcannon_1_1ray_1_1Camera.html", null ],
    [ "cannon::ray::CameraSample", "structcannon_1_1ray_1_1CameraSample.html", null ],
    [ "cannon::graphics::Character", "classcannon_1_1graphics_1_1Character.html", null ],
    [ "cannon::logic::Circuit", "structcannon_1_1logic_1_1Circuit.html", [
      [ "cannon::logic::AndGate", "structcannon_1_1logic_1_1AndGate.html", null ],
      [ "cannon::logic::FullAdder", "structcannon_1_1logic_1_1FullAdder.html", null ],
      [ "cannon::logic::NandGate", "structcannon_1_1logic_1_1NandGate.html", null ],
      [ "cannon::logic::NBitAdder", "structcannon_1_1logic_1_1NBitAdder.html", null ],
      [ "cannon::logic::OrGate", "structcannon_1_1logic_1_1OrGate.html", null ],
      [ "cannon::logic::XorGate", "structcannon_1_1logic_1_1XorGate.html", null ]
    ] ],
    [ "cannon::graphics::CircularBuffer", "structcannon_1_1graphics_1_1CircularBuffer.html", null ],
    [ "cannon::logic::Clause", "classcannon_1_1logic_1_1Clause.html", null ],
    [ "cannon::logic::CNFFormula", "classcannon_1_1logic_1_1CNFFormula.html", null ],
    [ "cannon::geom::ControlledTrajectory", "classcannon_1_1geom_1_1ControlledTrajectory.html", null ],
    [ "cannon::graphics::Cubemap", "classcannon_1_1graphics_1_1Cubemap.html", null ],
    [ "cannon::math::CubicSpline", "classcannon_1_1math_1_1CubicSpline.html", null ],
    [ "cannon::graphics::DeferredRenderer", "classcannon_1_1graphics_1_1DeferredRenderer.html", null ],
    [ "cannon::logic::DPLLState", "classcannon_1_1logic_1_1DPLLState.html", null ],
    [ "cannon::graphics::geometry::DrawableGeom", "classcannon_1_1graphics_1_1geometry_1_1DrawableGeom.html", [
      [ "cannon::graphics::geometry::AxesHint", "classcannon_1_1graphics_1_1geometry_1_1AxesHint.html", null ],
      [ "cannon::graphics::geometry::Cube", "classcannon_1_1graphics_1_1geometry_1_1Cube.html", null ],
      [ "cannon::graphics::geometry::Mesh", "classcannon_1_1graphics_1_1geometry_1_1Mesh.html", null ],
      [ "cannon::graphics::geometry::Model", "classcannon_1_1graphics_1_1geometry_1_1Model.html", null ],
      [ "cannon::graphics::geometry::Plane", "classcannon_1_1graphics_1_1geometry_1_1Plane.html", null ],
      [ "cannon::graphics::geometry::SDFVolume", "classcannon_1_1graphics_1_1geometry_1_1SDFVolume.html", null ]
    ] ],
    [ "cannon::physics::systems::DynamicCar", "classcannon_1_1physics_1_1systems_1_1DynamicCar.html", null ],
    [ "cannon::graphics::ElementBuffer", "classcannon_1_1graphics_1_1ElementBuffer.html", null ],
    [ "cannon::physics::EulerIntegrator< F >", "classcannon_1_1physics_1_1EulerIntegrator.html", null ],
    [ "cannon::physics::EulerIntegrator< cannon::physics::systems::PendSystem >", "classcannon_1_1physics_1_1EulerIntegrator.html", null ],
    [ "cannon::utils::ExperimentRunner", "classcannon_1_1utils_1_1ExperimentRunner.html", null ],
    [ "cannon::utils::ExperimentWriter", "classcannon_1_1utils_1_1ExperimentWriter.html", null ],
    [ "cannon::logic::FalseComparator", "structcannon_1_1logic_1_1FalseComparator.html", null ],
    [ "cannon::ray::Film", "classcannon_1_1ray_1_1Film.html", null ],
    [ "cannon::ray::FilmPixel", "structcannon_1_1ray_1_1FilmPixel.html", null ],
    [ "cannon::ray::FilmTile", "structcannon_1_1ray_1_1FilmTile.html", null ],
    [ "cannon::ray::Filter", "classcannon_1_1ray_1_1Filter.html", [
      [ "cannon::ray::BoxFilter", "classcannon_1_1ray_1_1BoxFilter.html", null ],
      [ "cannon::ray::GaussianFilter", "classcannon_1_1ray_1_1GaussianFilter.html", null ],
      [ "cannon::ray::MitchellFilter", "classcannon_1_1ray_1_1MitchellFilter.html", null ],
      [ "cannon::ray::TriangleFilter", "classcannon_1_1ray_1_1TriangleFilter.html", null ]
    ] ],
    [ "cannon::graphics::Font", "classcannon_1_1graphics_1_1Font.html", null ],
    [ "cannon::logic::Formula", "classcannon_1_1logic_1_1Formula.html", [
      [ "cannon::logic::And", "classcannon_1_1logic_1_1And.html", null ],
      [ "cannon::logic::Atomic", "classcannon_1_1logic_1_1Atomic.html", null ],
      [ "cannon::logic::Iff", "classcannon_1_1logic_1_1Iff.html", null ],
      [ "cannon::logic::Implies", "classcannon_1_1logic_1_1Implies.html", null ],
      [ "cannon::logic::Negation", "classcannon_1_1logic_1_1Negation.html", null ],
      [ "cannon::logic::Or", "classcannon_1_1logic_1_1Or.html", null ]
    ] ],
    [ "cannon::logic::FormulaState", "classcannon_1_1logic_1_1FormulaState.html", null ],
    [ "cannon::graphics::FragmentShader", "classcannon_1_1graphics_1_1FragmentShader.html", null ],
    [ "cannon::graphics::Framebuffer", "classcannon_1_1graphics_1_1Framebuffer.html", null ],
    [ "cannon::geom::Graph", "classcannon_1_1geom_1_1Graph.html", null ],
    [ "cannon::ray::hit_record", "structcannon_1_1ray_1_1hit__record.html", null ],
    [ "cannon::ray::Hittable", "classcannon_1_1ray_1_1Hittable.html", [
      [ "cannon::ray::Box", "classcannon_1_1ray_1_1Box.html", null ],
      [ "cannon::ray::BvhNode", "classcannon_1_1ray_1_1BvhNode.html", null ],
      [ "cannon::ray::ConstantMedium", "classcannon_1_1ray_1_1ConstantMedium.html", null ],
      [ "cannon::ray::HittableList", "classcannon_1_1ray_1_1HittableList.html", null ],
      [ "cannon::ray::MovingSphere", "classcannon_1_1ray_1_1MovingSphere.html", null ],
      [ "cannon::ray::Sphere", "classcannon_1_1ray_1_1Sphere.html", null ],
      [ "cannon::ray::Triangle", "classcannon_1_1ray_1_1Triangle.html", null ],
      [ "cannon::ray::XYRect", "classcannon_1_1ray_1_1XYRect.html", null ],
      [ "cannon::ray::XZRect", "classcannon_1_1ray_1_1XZRect.html", null ],
      [ "cannon::ray::YZRect", "classcannon_1_1ray_1_1YZRect.html", null ]
    ] ],
    [ "cannon::physics::systems::Holonomic2D", "classcannon_1_1physics_1_1systems_1_1Holonomic2D.html", null ],
    [ "cannon::graphics::ImageData", "structcannon_1_1graphics_1_1ImageData.html", null ],
    [ "cannon::control::InPort", "classcannon_1_1control_1_1InPort.html", null ],
    [ "cannon::physics::systems::InvertedPendulum", "classcannon_1_1physics_1_1systems_1_1InvertedPendulum.html", null ],
    [ "cannon::geom::KDTree", "classcannon_1_1geom_1_1KDTree.html", null ],
    [ "cannon::geom::KDTreeIndexed", "classcannon_1_1geom_1_1KDTreeIndexed.html", null ],
    [ "cannon::physics::systems::KinematicCar", "classcannon_1_1physics_1_1systems_1_1KinematicCar.html", null ],
    [ "cannon::graphics::Light", "classcannon_1_1graphics_1_1Light.html", [
      [ "cannon::graphics::DirectionalLight", "classcannon_1_1graphics_1_1DirectionalLight.html", null ],
      [ "cannon::graphics::PointLight", "classcannon_1_1graphics_1_1PointLight.html", null ],
      [ "cannon::graphics::Spotlight", "classcannon_1_1graphics_1_1Spotlight.html", null ]
    ] ],
    [ "cannon::graphics::LightCollection", "classcannon_1_1graphics_1_1LightCollection.html", null ],
    [ "cannon::plot::Line", "classcannon_1_1plot_1_1Line.html", null ],
    [ "cannon::logic::Literal", "classcannon_1_1logic_1_1Literal.html", null ],
    [ "cannon::physics::LocalTuple", "structcannon_1_1physics_1_1LocalTuple.html", null ],
    [ "cannon::log::Logger", "classcannon_1_1log_1_1Logger.html", null ],
    [ "cannon::control::LQRController", "classcannon_1_1control_1_1LQRController.html", null ],
    [ "cannon::ray::Material", "classcannon_1_1ray_1_1Material.html", [
      [ "cannon::ray::Dielectric", "classcannon_1_1ray_1_1Dielectric.html", null ],
      [ "cannon::ray::DiffuseLight", "classcannon_1_1ray_1_1DiffuseLight.html", null ],
      [ "cannon::ray::Isotropic", "classcannon_1_1ray_1_1Isotropic.html", null ],
      [ "cannon::ray::Lambertian", "classcannon_1_1ray_1_1Lambertian.html", null ],
      [ "cannon::ray::Metal", "classcannon_1_1ray_1_1Metal.html", null ],
      [ "cannon::ray::NormalDebug", "classcannon_1_1ray_1_1NormalDebug.html", null ]
    ] ],
    [ "cannon::graphics::geometry::Material", "structcannon_1_1graphics_1_1geometry_1_1Material.html", null ],
    [ "cannon::math::MonomialBasis", "classcannon_1_1math_1_1MonomialBasis.html", null ],
    [ "cannon::math::MultiSpline", "classcannon_1_1math_1_1MultiSpline.html", null ],
    [ "cannon::math::MultivariateNormal", "classcannon_1_1math_1_1MultivariateNormal.html", null ],
    [ "cannon::math::nth_derivative< F, T, N >", "classcannon_1_1math_1_1nth__derivative.html", null ],
    [ "cannon::math::nth_derivative< F, T, 1 >", "classcannon_1_1math_1_1nth__derivative_3_01F_00_01T_00_011_01_4.html", null ],
    [ "cannon::graphics::OpenGLState", "structcannon_1_1graphics_1_1OpenGLState.html", null ],
    [ "cannon::ml::OptimizationResult", "classcannon_1_1ml_1_1OptimizationResult.html", null ],
    [ "cannon::control::OutPort", "classcannon_1_1control_1_1OutPort.html", null ],
    [ "cannon::graphics::OverlayText", "structcannon_1_1graphics_1_1OverlayText.html", null ],
    [ "cannon::physics::Path", "structcannon_1_1physics_1_1Path.html", null ],
    [ "cannon::ml::PatternSearchOptimizer", "classcannon_1_1ml_1_1PatternSearchOptimizer.html", null ],
    [ "cannon::math::Perlin", "classcannon_1_1math_1_1Perlin.html", null ],
    [ "cannon::control::PidController", "classcannon_1_1control_1_1PidController.html", null ],
    [ "cannon::ml::PiecewiseILSTDFilter", "classcannon_1_1ml_1_1PiecewiseILSTDFilter.html", null ],
    [ "cannon::ml::PiecewiseLSTDFilter", "classcannon_1_1ml_1_1PiecewiseLSTDFilter.html", null ],
    [ "cannon::ml::PiecewiseRecursiveLSTDFilter", "classcannon_1_1ml_1_1PiecewiseRecursiveLSTDFilter.html", null ],
    [ "cannon::plot::Plotter", "classcannon_1_1plot_1_1Plotter.html", null ],
    [ "cannon::plot::Polygon", "classcannon_1_1plot_1_1Polygon.html", null ],
    [ "cannon::math::Polynomial< Basis >", "classcannon_1_1math_1_1Polynomial.html", null ],
    [ "cannon::math::Polynomial< cannon::math::MonomialBasis >", "classcannon_1_1math_1_1Polynomial.html", null ],
    [ "cannon::logic::PropositionHeuristic", "classcannon_1_1logic_1_1PropositionHeuristic.html", null ],
    [ "cannon::logic::RandomComparator", "structcannon_1_1logic_1_1RandomComparator.html", null ],
    [ "cannon::ray::Ray", "classcannon_1_1ray_1_1Ray.html", null ],
    [ "cannon::ray::Raytracer", "classcannon_1_1ray_1_1Raytracer.html", null ],
    [ "cannon::ray::raytracer_params", "structcannon_1_1ray_1_1raytracer__params.html", null ],
    [ "cannon::log::Registry", "classcannon_1_1log_1_1Registry.html", null ],
    [ "cannon::graphics::RenderPass", "classcannon_1_1graphics_1_1RenderPass.html", null ],
    [ "cannon::physics::RK4Integrator", "classcannon_1_1physics_1_1RK4Integrator.html", null ],
    [ "cannon::ml::RLSFilter", "classcannon_1_1ml_1_1RLSFilter.html", null ],
    [ "cannon::ray::Sampler", "classcannon_1_1ray_1_1Sampler.html", [
      [ "cannon::ray::GlobalSampler", "classcannon_1_1ray_1_1GlobalSampler.html", null ],
      [ "cannon::ray::PixelSampler", "classcannon_1_1ray_1_1PixelSampler.html", [
        [ "cannon::ray::StratifiedSampler", "classcannon_1_1ray_1_1StratifiedSampler.html", null ]
      ] ]
    ] ],
    [ "cannon::plot::Scatter", "classcannon_1_1plot_1_1Scatter.html", null ],
    [ "cannon::graphics::geometry::ScreenQuad", "classcannon_1_1graphics_1_1geometry_1_1ScreenQuad.html", null ],
    [ "cannon::graphics::ShaderProgram", "classcannon_1_1graphics_1_1ShaderProgram.html", null ],
    [ "cannon::control::Signal", "classcannon_1_1control_1_1Signal.html", null ],
    [ "cannon::graphics::geometry::Skybox", "classcannon_1_1graphics_1_1geometry_1_1Skybox.html", null ],
    [ "cannon::utils::StatRegisterer", "classcannon_1_1utils_1_1StatRegisterer.html", null ],
    [ "cannon::utils::StatsAccumulator", "classcannon_1_1utils_1_1StatsAccumulator.html", null ],
    [ "cannon::physics::systems::System", "classcannon_1_1physics_1_1systems_1_1System.html", [
      [ "cannon::physics::systems::DynamicCarSystem", "structcannon_1_1physics_1_1systems_1_1DynamicCarSystem.html", null ],
      [ "cannon::physics::systems::Hol2DSystem", "structcannon_1_1physics_1_1systems_1_1Hol2DSystem.html", null ],
      [ "cannon::physics::systems::KinCarSystem", "structcannon_1_1physics_1_1systems_1_1KinCarSystem.html", null ],
      [ "cannon::physics::systems::PendSystem", "structcannon_1_1physics_1_1systems_1_1PendSystem.html", null ]
    ] ],
    [ "cannon::graphics::TextBoundingBox", "structcannon_1_1graphics_1_1TextBoundingBox.html", null ],
    [ "cannon::graphics::TextRenderer", "classcannon_1_1graphics_1_1TextRenderer.html", null ],
    [ "cannon::graphics::Texture", "classcannon_1_1graphics_1_1Texture.html", null ],
    [ "cannon::ray::Texture", "classcannon_1_1ray_1_1Texture.html", [
      [ "cannon::ray::CheckerTexture", "classcannon_1_1ray_1_1CheckerTexture.html", null ],
      [ "cannon::ray::ImageTexture", "classcannon_1_1ray_1_1ImageTexture.html", null ],
      [ "cannon::ray::NoiseTexture", "classcannon_1_1ray_1_1NoiseTexture.html", null ],
      [ "cannon::ray::SolidColor", "classcannon_1_1ray_1_1SolidColor.html", null ]
    ] ],
    [ "cannon::utils::ThreadPool< T >", "classcannon_1_1utils_1_1ThreadPool.html", null ],
    [ "cannon::utils::ThreadPool< cannon::graphics::ImageData >", "classcannon_1_1utils_1_1ThreadPool.html", null ],
    [ "cannon::geom::Trajectory", "classcannon_1_1geom_1_1Trajectory.html", null ],
    [ "cannon::ray::TriangleMesh", "classcannon_1_1ray_1_1TriangleMesh.html", null ],
    [ "cannon::logic::TwoClauseComparator", "structcannon_1_1logic_1_1TwoClauseComparator.html", null ],
    [ "cannon::graphics::VertexArrayObject", "classcannon_1_1graphics_1_1VertexArrayObject.html", null ],
    [ "cannon::graphics::VertexBuffer", "classcannon_1_1graphics_1_1VertexBuffer.html", null ],
    [ "cannon::graphics::VertexShader", "classcannon_1_1graphics_1_1VertexShader.html", null ],
    [ "cannon::graphics::Viewer3D", "classcannon_1_1graphics_1_1Viewer3D.html", null ],
    [ "cannon::logic::VsidsComparator", "structcannon_1_1logic_1_1VsidsComparator.html", null ],
    [ "cannon::graphics::Window", "classcannon_1_1graphics_1_1Window.html", null ]
];