name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: '${{ secrets.MY_GITHUB_PAT }}'
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cannon/cannon
      
    - name: Run container
      run: docker run cannon/cannon
